DATABASE_OBJECT_TYPE=
['Action List',
'Alert Definition List',
'Alert Instance List',
'Asset Group',
'Asset Network',
'Asset Network Template',
'Asset Validation',
'Assimilation',
'Calibration',
'Collection Cost Estimator',
'Collection Inference',
'Collection Network',
'Collection Network Template',
'Collection Validation',
'Custom Graph',
'Custom Report',
'Damage Calculation Results',
'Damage Function',
'Dashboard',
'Distribution Cost Estimator',
'Distribution Inference',
'Distribution Network',
'Distribution Network Template',
'Distribution Validation',
'Episode Collection',
'Flow Survey',
'Geo Explorer',
'Graph',
'Gridded Ground Model',
'Ground Infiltration',
'Ground Model',
'Infinity Configuration',
'Inflow',
'Initial Conditions 1D',
'Initial Conditions 2D',
'Initial Conditions Catchment',
'Label List',
'Layer List',
'Level',
'Lifetime Estimator',
'Live Group',
'Manifest',
'Manifest Deployment',
'Master Group',
'Model Group',
'Model Inference',
'Model Network',
'Model Network Template',
'Model Validation',
'Observed Depth Event',
'Observed Flow Event',
'Observed Velocity Event',
'Pipe Sediment Data',
'Point Selection',
'Pollutant Graph',
'Print Layout',
'Rainfall Event',
'Regulator',
'Rehabilitation Planner',
'Risk Analysis Run',
'Risk Assessment',
'Risk Calculation Results',
'Run',
'Selection List',
'Sim',
'Sim Stats',
'Statistics Template',
'Stored Query',
'Theme',
'Time Varying Data',
'Trade Waste',
'TSDB',
'TSDB Spatial',
'UPM River Data',
'UPM Threshold',
'Waste Water',
'Workspace']